const messages = {
  en: {
    bookNotFound: "Book not found",
    libraryNotFound: "Library not found",
    invalidCredentials: "Invalid credentials",
    bookAlreadyBorrowed: "Book is already borrowed",
    bookNotBorrowed: "Book is not borrowed",
    errorFetchingBooks: "Error fetching books",
    errorFetchingBook: "Error fetching book",
    errorCreatingBook: "Error creating book",
    errorUpdatingBook: "Error updating book",
    errorDeletingBook: "Error deleting book",
    bookBorrowedSuccessfully: "Book borrowed successfully",
    bookReturnedSuccessfully: "Book returned successfully",
    userRegisteredSuccessfully: "User registered successfully",
    loginSuccessful: "Login successful",
    errorRegisteringUser: "Error registering user",
    errorLoggingIn: "Error logging in",
    errorFetchingLibraries: "Error fetching libraries",
    errorFetchingLibrary: "Error fetching library",
    errorCreatingLibrary: "Error creating library",
    errorUpdatingLibrary: "Error updating library",
    errorDeletingLibrary: "Error deleting library",
    internalServerError: "Internal server error",
  },
  hi: {
    bookNotFound: "पुस्तक नहीं मिली",
    libraryNotFound: "पुस्तकालय नहीं मिला",
    invalidCredentials: "अमान्य क्रेडेंशियल्स",
    bookAlreadyBorrowed: "पुस्तक पहले से ही उधार ली गई है",
    bookNotBorrowed: "पुस्तक उधार नहीं ली गई है",
    errorFetchingBooks: "पुस्तकें लाने में त्रुटि",
    errorFetchingBook: "पुस्तक लाने में त्रुटि",
    errorCreatingBook: "पुस्तक बनाने में त्रुटि",
    errorUpdatingBook: "पुस्तक अपडेट करने में त्रुटि",
    errorDeletingBook: "पुस्तक हटाने में त्रुटि",
    bookBorrowedSuccessfully: "पुस्तक सफलतापूर्वक उधार ली गई",
    bookReturnedSuccessfully: "पुस्तक सफलतापूर्वक वापस की गई",
    userRegisteredSuccessfully: "उपयोगकर्ता सफलतापूर्वक पंजीकृत हुआ",
    loginSuccessful: "लॉगिन सफल",
    errorRegisteringUser: "उपयोगकर्ता पंजीकरण में त्रुटि",
    errorLoggingIn: "लॉगिन में त्रुटि",
    errorFetchingLibraries: "पुस्तकालय लाने में त्रुटि",
    errorFetchingLibrary: "पुस्तकालय लाने में त्रुटि",
    errorCreatingLibrary: "पुस्तकालय बनाने में त्रुटि",
    errorUpdatingLibrary: "पुस्तकालय अपडेट करने में त्रुटि",
    errorDeletingLibrary: "पुस्तकालय हटाने में त्रुटि",
    internalServerError: "सर्वर त्रुटि",
  },
};

export const getMessage = (key, lang = "en") => {
  return messages["en"][key] || key;
};
